import { size, themes, type SemanticColors, type ThemeName } from './semantic';

const PREFIX = '--bh';

/** `bgHover` → `bg-hover`, so generated CSS reads like CSS. */
const kebab = (segment: string) => segment.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/**
 * Flattens a nested token object into CSS custom property declarations.
 * `text.muted` becomes `--bh-text-muted`.
 */
function flatten(value: unknown, path: string[] = []): Array<[string, string]> {
  if (typeof value === 'string') {
    return [[`${PREFIX}-${path.map(kebab).join('-')}`, value]];
  }
  if (typeof value === 'object' && value !== null) {
    return Object.entries(value).flatMap(([key, child]) => flatten(child, [...path, key]));
  }
  return [];
}

export function toCssVariables(theme: SemanticColors): Array<[string, string]> {
  return [...flatten(theme), ...flatten(size)];
}

/**
 * Reference a semantic token from component CSS or inline styles.
 * `cssVar('text.muted')` → `var(--bh-text-muted)`.
 */
export function cssVar(path: string): string {
  return `var(${PREFIX}-${path.split('.').map(kebab).join('-')})`;
}

/** The full stylesheet: light on `:root`, dark under an explicit attribute
 *  and under `prefers-color-scheme` for users who never touched a toggle. */
export function renderStylesheet(): string {
  const block = (declarations: Array<[string, string]>, indent = '  ') =>
    declarations.map(([name, value]) => `${indent}${name}: ${value};`).join('\n');

  const themeBlock = (name: ThemeName) => block(toCssVariables(themes[name]));

  return `/* Generated by scripts/build-tokens.ts — do not edit by hand. */

:root {
${themeBlock('light')}

  --bh-font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
  color-scheme: light;
}

:root[data-theme='dark'] {
${themeBlock('dark')}
  color-scheme: dark;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${block(toCssVariables(themes.dark), '    ')}
    color-scheme: dark;
  }
}
`;
}
